name: CI/CD

on:
  push:
    branches:
      - main # A pipeline será executada a cada push na branch main

jobs:
  build:
    runs-on: ubuntu-latest # Configurando a maquina virtual de teste

    steps:
      - name: Checkout código # Faz um git clone da nossa branch, e chega o código
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2 # Configurando o a,biente java
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Construir com Maven # Incluindo as dependencias
        run: mvn -B clean package

#      - name: Executar testes # Executando os testes
#        run: mvn test
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código # Faz um git clone da nossa branch, e chega o código
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2 # Configurando o ambiente java
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests with Maven
        run: mvn test # Comando para executar os testes do projeto

