name: Java CI

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest # Configurando a maquina virtual de teste

    steps:
      - name: Checkout c贸digo # Faz um git clone da nossa branch, e chega o c贸digo
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2 # Configurando o ambiente java
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Construir com Maven # Incluindo as dependencias
        run: mvn clean install -B -V

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout c贸digo # Faz um git clone da nossa branch, e chega o c贸digo
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2 # Configurando o ambiente java
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests with Maven
        run: mvn test # Comando para executar os testes do projeto