name: CI/CD

on:
  push:
    branches:
      - main # A pipeline será executada a cada push na branch main

jobs:
  build:
    runs-on: ubuntu-latest # Configurando a maquina virtual de teste

    steps:
      - name: Checkout código # Faz um git clone da nossa branch, e chega o código
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2 # Configurando o a,biente java
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Construir com Maven # Incluindo as dependencias
        run: mvn -B clean package

      - name: Executar testes # Executando os testes
        run: mvn test

      - name: Iniciar aplicativo Spring Boot com H2 (usado apenas para fins de exemplo)
        run: mvn spring-boot:run


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

#      - name: Iniciar aplicativo Spring Boot com H2 (usado apenas para fins de exemplo)
#        run: mvn spring-boot:run
